<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXoprscb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXoprscb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXoprscb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXoprscb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXoprscb\appProdProjectContainer([
    'container.build_hash' => 'Xoprscb',
    'container.build_id' => 'ecc3fe3d',
    'container.build_time' => 1615948928,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXoprscb');
